dataset:
  name: rrfs_15km_example
  coor_file: 15km_rrfs-grib-grid_xy_coordinates.npy 
  bc_mask_file: 15km_border_mask.npy
  gp_surface_file: 15km_rrfs-gp_surface.npy
  var_names:
    - pres_0g
    - hgt_500
    - ugrd_925
    - ugrd_850 
    - ugrd_500 
    - ugrd_200 
    - vgrd_925
    - vgrd_850 
    - vgrd_500 
    - vgrd_200 
    - temp_925
    - temp_850 
    - temp_500 
    - temp_200 
    - sphum_925
    - sphum_850 
    - sphum_500 
    - sphum_200 
    - clmr_925
    - clmr_850 
    - clmr_500 
    - clmr_200 
    - icmr_925
    - icmr_850 
    - icmr_500 
    - icmr_200 
    - rwmr_925
    - rwmr_850 
    - rmwr_500 
    - rwmr_200 
    - snmr_925
    - snmr_850 
    - snmr_500 
    - snmr_200 
    - grle_925
    - grle_850 
    - grle_500 
    - grle_200 
    - temp_sfc
    - tcdc
    - refc 
  var_units:
    - Pa
    - gpm 
    - m/s
    - m/s
    - m/s
    - m/s
    - m/s
    - m/s
    - m/s
    - m/s
    - K
    - K
    - K
    - K
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - kg/kg
    - K
    - None 
    - dB
  var_longnames:
    - pres_heightAboveGround_0_instant
    - gpm_pressureAbove500hpa_0_instant
    - u_isobaricInhPa_925_instant
    - u_isobaricInhPa_850_instant
    - u_isobaricInhPa_500_instant
    - u_isobaricInhPa_200_instant
    - v_isobaricInhPa_925_instant
    - v_isobaricInhPa_850_instant
    - v_isobaricInhPa_500_instant
    - v_isobaricInhPa_200_instant
    - temp_isobaricInhPa_925_instant
    - temp_isobaricInhPa_850_instant
    - temp_isobaricInhPa_500_instant
    - temp_isobaricInhPa_200_instant
    - sphum_isobaricInhPa_925_instant
    - sphum_isobaricInhPa_850_instant
    - sphum_isobaricInhPa_500_instant
    - sphum_isobaricInhPa_200_instant
    - clmr_isobaricInhPa_925_instant
    - clmr_isobaricInhPa_850_instant
    - clmr_isobaricInhPa_500_instant
    - clmr_isobaricInhPa_200_instant
    - icmr_isobaricInhPa_925_instant
    - icmr_isobaricInhPa_850_instant
    - icmr_isobaricInhPa_500_instant
    - icmr_isobaricInhPa_200_instant
    - rwmr_isobaricInhPa_925_instant
    - rwmr_isobaricInhPa_850_instant
    - rwmr_isobaricInhPa_500_instant
    - rwmr_isobaricInhPa_200_instant
    - snmr_isobaricInhPa_925_instant
    - snmr_isobaricInhPa_850_instant
    - snmr_isobaricInhPa_500_instant
    - snmr_isobaricInhPa_200_instant
    - grle_isobaricInhPa_925_instant
    - grle_isobaricInhPa_850_instant
    - grle_isobaricInhPa_500_instant
    - grle_isobaricInhPa_200_instant
    - temperature_surface_0_instant
    - tcdc_TotalCloudCover_entireAtmosphere_0_instant
    - refc_CompositeReflectivity_entireAtmosphere_0_instant

  num_forcing_features: 16
grid_shape_state: [211, 359]
projection:
  class: LambertConformal
  kwargs:
    central_longitude: -97.5  # Converted from LoV 262.5 degrees as 360 - 262.5 = 97.5
    central_latitude: 38.5  # Directly from LatD (Latitude of origin)
    standard_parallels: [38.5, 38.5]  # From Latin1 and Latin2

